sudo: required

language: rust
cache: cargo

services: docker

rust: nightly

os: linux

install:
  - export PATH="$PATH:/home/travis/.cargo/bin"
  - command -v ghp >/dev/null 2>&1 || cargo install ghp --debug
  # TODO use versioned release instead of git snapshot
  - command -v mdbook >/dev/null 2>&1 || cargo install --git https://github.com/azerupi/mdbook --debug --no-default-features --features output

script:
  - bash ci/script.sh

after_success:
  - bash ci/after_success.sh

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
  webhooks: https://homu.herokuapp.com/travis

env:
  global:
    - secure: kJof1o+nrjiqS+w8TDDTxhApprxcjksSeovpumuc9eCMGK+4mqtjdl7AGP9AYbIYWAJEF80FJTvXyzviZs7Ov+K52YuLXVkfGSM4v1Gm9NZol6H208QLmggBhsbNzyu3v+/RUTVE3foDAANxhOVXSlLRc8thd9TfzFMRHhna63uNDNLbzE7A1a/etPGLe6QSIGXlQ/EKNUGxA2vTr15xlzm5qmLILHIEGuLEw8IMk0dd8eDYF+vQuQXFnWYL3Wx1MCqk88OK9KpMNR4Rujuewsgb3ODM56y67mRnMyu1wXoN4idXaeGy2S/M3XCdwY0vt/7WTkluTGQ3PQu8tsM5unV50/1x78xw7uEsMFd7g5IJXrsZB00vrrgXjJ/6oOZcNWhWX+LdPa+keyBau6KedPhVt9yFqhgeDIh8+qIDfVGzMmvCN8rcmWQc5z8f370kD7B9/oNp8FPazpU83gtCuWdKLKtxigVCNZWLxiMnH/y4fmNJUqOY0wbyDucNO+io72MNQTLIw5eMNWV7FDgU2pbexckUq763ZmhBhMYwo8e1583mi8jJy8j/hHYWFA4hsnA/5McdBUqxuWZLg2RgB9mJ8EYAJkGE4g2TR+W9GX6pj/xfQ7jLUe8HBgqUKBtDAMz/ZtpU1kpb4IQb1b6uoZci/zWBwCGRGtzJtzak064=
